services:
  api1:
    image: node:22-alpine
    container_name: api1Nodejs
    working_dir: /app
    volumes:
      - ./apis-node/api1:/app
    command: sh -c "npm install && node src/app.js"
    ports:
      - '3001:3000'
    environment:
      - PORT=3000
    networks:
      - app-network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  api2:
    image: node:22-alpine
    container_name: api2Nodejs
    working_dir: /app
    volumes:
      - ./apis-node/api2:/app
    command: sh -c "npm install && node src/app.js"
    ports:
      - '3002:3000'
    environment:
      - PORT=3000
      - HOSTUSER=http://api1:3000
    networks:
      - app-network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - app-network

  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    user: '${UID:-1000}:${GID:-1000}'
    ports:
      - 443:8080
    volumes:
      - ./file-browser/data:/data
      - ./file-browser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
