openapi: 3.0.0
info:
  title: API Node Template
  description: API Description
  version: 1.0.0
  contact:
    name: Nombre Desarrollador
    email: mail.desarrollador@weplan-latam.com
servers:
  - url: '{protocol}://{url}/{basePath}'
    description: Local Server
    variables:
      url:
        enum:
          - localhost:3000
        default: localhost:3000
      protocol:
        enum:
          - http
          - https
        default: http
      basePath:
        enum:
          - base-path
        default: base-path
# Down comments are an example of use
paths:
  /:
    get:
      summary: Check health
      tags:
        - Health
      produces:
        - application/json
      responses:
        200: # status code
          description: Object response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 'Welcome'
# /pathName:
#     get:
#         summary: Customer Attention Centers - GET customer attention centers info by coordenates
#         tags:
#             - Customer Attention Centers
#         parameters:
#             - name: typeCenter
#               description: Type of attention center to filter
#               in: path
#               required: true
#               schema:
#                   type: string
#                   enum:
#                       - cacs
#                       - pacs
#             - name: lat
#               description: North equator distance
#               in: path
#               required: true
#               schema:
#                   type: string
#                   example: -34.6201024128077
#             - name: lath
#               description: South equator distance
#               in: path
#               required: true
#               schema:
#                   type: string
#                   example: -34.58619152537777
#             - name: lng
#               description: East equator distance
#               in: path
#               required: true
#               schema:
#                   type: string
#                   example: -58.483067524353025
#             - name: lngh
#               description: West equator distance
#               in: path
#               required: true
#               schema:
#                   type: string
#                   example: -58.33861447564697
#         produces:
#             - application/json
#         responses:
#             200: # status code
#                 description: A JSON array of objects
#                 content:
#                     application/json:
#                         schema:
#                             type: array
#                             items:
#                                 type: object
